name: Bazel CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  bazel:
    name: Bazel Build & Test
    runs-on: ubuntu-latest
    env:
      BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Bazelisk (Bazel version manager)
        uses: bazelbuild/setup-bazelisk@v1

      - name: Ensure Cache Path Exists
        run: |
          mkdir -p ~/.cache/bazel

      - name: Restore Bazel Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
          key: bazel-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            bazel-${{ runner.os }}-

      - name: Debug Cache
        run: |
          echo "Cache key: bazel-${{ runner.os }}-${{ github.sha }}"
          ls -la ~/.cache/bazel || echo "Cache directory does not exist or is empty."

      - name: Determine changed targets
        id: changes
        run: |
          CHANGED_FILES=$(git diff --name-only origin/main | sed 's|^|//|' | paste -sd ' ')
          echo "CHANGED=$(bazel query \"kind('.*', rdeps(//..., set($CHANGED_FILES)))\" || echo '')" >> $GITHUB_ENV
      - name: Build Changed Targets
        if: env.CHANGED != ''
        run: |
          bazel build $CHANGED

      - name: Test Changed Targets
        if: env.CHANGED != ''
        run: |
          bazel test $CHANGED --test_output=errors

      - name: Upload Test Logs on Failure
        if: failure()
        run: |
          if [ -d bazel-testlogs ]; then
            find bazel-testlogs -name "test.log" -exec cat {} \;
          else
            echo "No test logs to upload."
          fi
